### ISSUE TITLE
TypeError: download_songs() got an unexpected keyword argument 'manual'

### ISSUE THREAD

**Issue by yuriy636** [pepershukov/ytm-yld#3]
With this config

```ini
[ytm-yld]
cookie = C:\Users\yuriy\Downloads\music.youtube.com_cookies.txt
mode = m
json = C:\Users\yuriy\Music\ytm-yld\metadata.json
songs-json = C:\Users\yuriy\Music\ytm-yld\songs_metadata.json
output = C:\Users\yuriy\Music\ytm-yld

no-cover = True
no-lyrics = True
```

Upon selecting the desired song number I'm getting this:

> [2023-05-27 12:28:31.133748] [INPUT] [playlistmanual 34] Enter the song numbers you wish to download (e.g. 1-5,12,7-9,10):
> \> 3
> Traceback (most recent call last):
>   File "main.py", line 349, in <module>
> TypeError: download_songs() got an unexpected keyword argument 'manual'
> [20456] Failed to execute script 'main' due to unhandled exception!

## Notes

- Windows 10
- ytm-yld version 8.0.0

**Comment by pepershukov** [comment]
I forgot to remove the argument that was passed to the function. Simple as that 😅 Because of it unfortunately, manual mode isn't usable.

Sorry about that. I will include this issue in the following hotfix

**Comment by pepershukov** [comment]
I pushed a hotfix [v8.0.1](https://github.com/pepershukov/ytm-yld/releases/tag/v8.0.1), hopefully fixing the issue.

Still though, if anything is wrong, let me know.
